// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customer/customer.proto

package Netxd_Project1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Customer struct {
	CustomerID           int32    `protobuf:"varint,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	BankID               int32    `protobuf:"varint,4,opt,name=BankID,proto3" json:"BankID,omitempty"`
	Balance              int32    `protobuf:"varint,5,opt,name=Balance,proto3" json:"Balance,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	IsActive             bool     `protobuf:"varint,8,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52c63852255b1ea, []int{0}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetCustomerID() int32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *Customer) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Customer) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Customer) GetBankID() int32 {
	if m != nil {
		return m.BankID
	}
	return 0
}

func (m *Customer) GetBalance() int32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Customer) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Customer) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Customer) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type CustomerResponse struct {
	CustomerID           int32    `protobuf:"varint,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerResponse) Reset()         { *m = CustomerResponse{} }
func (m *CustomerResponse) String() string { return proto.CompactTextString(m) }
func (*CustomerResponse) ProtoMessage()    {}
func (*CustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52c63852255b1ea, []int{1}
}

func (m *CustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerResponse.Unmarshal(m, b)
}
func (m *CustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerResponse.Marshal(b, m, deterministic)
}
func (m *CustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerResponse.Merge(m, src)
}
func (m *CustomerResponse) XXX_Size() int {
	return xxx_messageInfo_CustomerResponse.Size(m)
}
func (m *CustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerResponse proto.InternalMessageInfo

func (m *CustomerResponse) GetCustomerID() int32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *CustomerResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*Customer)(nil), "netxd_customer.Customer")
	proto.RegisterType((*CustomerResponse)(nil), "netxd_customer.CustomerResponse")
}

func init() {
	proto.RegisterFile("customer/customer.proto", fileDescriptor_f52c63852255b1ea)
}

var fileDescriptor_f52c63852255b1ea = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x49, 0xdf, 0xb7, 0x6d, 0x3a, 0x87, 0x2a, 0x7b, 0xd0, 0xa5, 0x88, 0x84, 0x5e, 0x8c,
	0x07, 0x13, 0xd4, 0x4f, 0x90, 0xb4, 0x0a, 0xc1, 0x10, 0x42, 0x8a, 0x1e, 0xbc, 0x94, 0xed, 0x66,
	0xd0, 0xa8, 0xc9, 0x86, 0xcd, 0xb6, 0xf8, 0xa9, 0xfd, 0x0c, 0x92, 0x3f, 0x9b, 0xaa, 0x20, 0x78,
	0x9b, 0xe7, 0xf9, 0xed, 0xee, 0x3c, 0x33, 0x0b, 0xc7, 0x7c, 0x5b, 0x29, 0x91, 0xa3, 0x74, 0x75,
	0xe1, 0x94, 0x52, 0x28, 0x41, 0xa6, 0x05, 0xaa, 0xf7, 0x74, 0xad, 0xdd, 0xf9, 0x87, 0x01, 0xe6,
	0xa2, 0x13, 0xe4, 0x14, 0x40, 0xd7, 0xc1, 0x92, 0x1a, 0x96, 0x61, 0x0f, 0x93, 0x2f, 0x0e, 0x39,
	0x81, 0xc9, 0x6d, 0x26, 0x2b, 0x15, 0xb1, 0x1c, 0xe9, 0xc0, 0x32, 0xec, 0x49, 0xb2, 0x37, 0xc8,
	0x0c, 0xcc, 0x90, 0x75, 0xf0, 0x5f, 0x03, 0x7b, 0x4d, 0x8e, 0x60, 0xe4, 0xb3, 0xe2, 0x35, 0x58,
	0xd2, 0xff, 0xcd, 0xab, 0x9d, 0x22, 0x14, 0xc6, 0x3e, 0x7b, 0x63, 0x05, 0x47, 0x3a, 0x6c, 0x80,
	0x96, 0x75, 0xaf, 0x85, 0x44, 0xa6, 0x30, 0xf5, 0x14, 0x1d, 0xb5, 0xbd, 0x7a, 0xa3, 0xa6, 0xf7,
	0x65, 0xda, 0xd1, 0x71, 0x4b, 0x7b, 0xa3, 0x4e, 0x12, 0x54, 0x1e, 0x57, 0xd9, 0x0e, 0xa9, 0x69,
	0x19, 0xb6, 0x99, 0xf4, 0x7a, 0x1e, 0xc3, 0xa1, 0x9e, 0x28, 0xc1, 0xaa, 0x14, 0x45, 0x85, 0x7f,
	0x99, 0x7b, 0x9f, 0x65, 0xf0, 0x23, 0xcb, 0xd5, 0x1a, 0x0e, 0xf4, 0xd9, 0x15, 0xca, 0x5d, 0xc6,
	0x91, 0x84, 0x30, 0x6d, 0x79, 0xbf, 0x5a, 0xea, 0x7c, 0x5f, 0xbc, 0xa3, 0xc9, 0xcc, 0xfa, 0x8d,
	0xe8, 0x78, 0xfe, 0xf9, 0xe3, 0xd9, 0x53, 0xa6, 0x9e, 0xb7, 0x1b, 0x87, 0x8b, 0xdc, 0x5d, 0xdd,
	0x84, 0x0f, 0xde, 0x9d, 0x17, 0x45, 0x5e, 0x74, 0x11, 0xbb, 0x51, 0x73, 0x37, 0x96, 0xe2, 0x05,
	0xb9, 0xba, 0xdc, 0x8c, 0x9a, 0x5f, 0xbe, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x06, 0xd5,
	0xbf, 0x00, 0x02, 0x00, 0x00,
}
